[package]
name = "phyloalifold"
version = "0.1.2"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "PhyloAliFold Program, which Predicts RNA Consensus Secondary Structures to Incorporate Phylogeny among Homologs"
repository = "https://github.com/heartsh/phyloalifold"
readme = "README.md"
keywords = ["bioinformatics", "rna", "secondary-structure"]
license = "MIT"

[dependencies]
num_cpus = "1.0"
bio = "0.20"
phyloprob = "0.1"
phylofold = "0.1"

[lib]
path = "src/lib.rs"
name = "phyloalifold"
