[package]
name = "phyloalifold"
version = "0.1.0"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "PhyloAliFold Program, which predicts RNA Consensus Secondary Structures to Incorporate Phylogeny among Homologs"

[dependencies]
rna-algos = "0.1"
getopts = "0.2"
phyloprob = "0.1"
phylofold = "0.1"

[lib]
path = "src/lib.rs"
name = "phyloalifold"
