[package]
name = "consalifold"
version = "0.1.1"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "ConsAlifold, which Predicts Global Consensus RNA Secondary Structures to Consider Sparse Global Pairwise RNA Structural Alignments"
repository = "https://github.com/heartsh/consalifold"
readme = "README.md"
keywords = ["bioinformatics", "rna", "secondary-structure"]
license = "MIT"

[dependencies]
num_cpus = "1.0"
bio = "0.20"
# consprob = "0.1"
consprob = {path = "../consprob"}
# conshomfold = "0.1"
conshomfold = {path = "../conshomfold"}

[lib]
path = "src/lib.rs"
name = "consalifold"
